default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  username: weekly_workshop

development:
  <<: *default
  database: zoo_development

test:
  <<: *default
  database: zoo_test
